<a href="https://colab.research.google.com/github/sandhiyasivanandanx/Assessment2_Numpy-Pandas/blob/main/Assessment2_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SECTION A**

**Q1.** NumPy Array Creation

Create a NumPy array containing the following values:
10, 20, 30, 40, 50
Display:
The array
Shape of the array
Data type of the array

In [9]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.dtype)

[10 20 30 40 50]
(5,)
int64

**Q2.** NumPy Array Operations

Given:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
Using NumPy:
Add 5 to every element.
Multiply every element by 2.
Display the results.

In [14]:
import numpy as np
arr = np.array([5,10,15,20,25])
print("Adding 5 To Every Element : ", arr+5)
print("Multiply every element by 2 : ", arr*2)

Adding 5 To Every Element :  [10 15 20 25 30]
Multiply every element by 2 :  [10 20 30 40 50]

**Q3.** NumPy Statistical Operations

Given:
arr = np.array([12, 15, 18, 20, 25, 30])
Using NumPy, calculate:
Mean
Median
Minimum
Maximum
Standard deviation

In [21]:
import numpy as np
arr = np.array([12,15,18,20,25,30])
mean = np.mean(arr)
median = np.median(arr)
minimum = np.min(arr)
maximum = np.max(arr)
std = np.std(arr)
print("Mean : ",mean)
print("Median : ",median)
print("Minimum : ",minimum)
print("Maximum : ",maximum)
print("Standard Deviation : ",std)

Mean :  20.0
Median :  19.0
Minimum :  12
Maximum :  30
Standard Deviation :  6.027713773341708

**Q4.** NumPy Filtering

Given:
arr = np.array([10, 25, 30, 45, 50, 65, 70])
Using NumPy, extract all values that are greater than 40.

In [22]:
import numpy as np
arr = np.array([10,25,30,45,50,65,70])
print(arr[arr>40])

[45 50 65 70]

**Q5.** Create a Pandas DataFrame

Create the following DataFrame using Pandas:
Name Age Score
Anu 21 85
Rahul 22 72
Meera 20 91
Arun 23 68
Display the DataFrame.

In [25]:
import pandas as pd
df = pd.DataFrame({
    'Name':['Anu','Rahul','Meera','Arun'],
    'Age':[21,22,20,23],
    'Score':[85,72,91,68]
})
print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

**Q6.** DataFrame Selection

Using the DataFrame created in Q5:
Display only the Name and Score columns.
Display the complete record of Meera .

In [29]:
print(df[['Name','Score']])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

In [30]:
print(df[df['Name']=='Meera'])

    Name  Age  Score
2  Meera   20     91

**Q7.** DataFrame Filtering

Using the DataFrame from Q5, display all students whose Score is greater than 75

In [34]:
print(df[df['Score'] > 75])

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

**Q8.** DataFrame Inspection
Using the DataFrame from Q5, display:
Number of rows and columns
Column names
Data types
Basic statistical summary

In [36]:
print("Rows and Columns:", df.shape)

Rows and Columns: (4, 3)

In [37]:
print("Column Names:", df.columns)

Column Names: Index(['Name', 'Age', 'Score'], dtype='object')

In [39]:
print(df.dtypes)

Name     object
Age       int64
Score     int64
dtype: object

In [42]:
print("Statistical Summary:")
print(df.describe())

Statistical Summary:
             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

**Q9.** Sorting a DataFrame

Sort the DataFrame from Q5 by Score in descending order.

In [45]:
df.sort_values(by='Score', ascending=False)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

**Q10.** Handling Missing Values

Consider the following DataFrame:
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})

Write Pandas code to:
Identify the missing values.
Replace the missing Age with the mean age.
Replace the missing Score with the mean score.

In [52]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [21, np.nan, 23, 22],
    'Score': [80, 75, np.nan, 90]
})
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Score'] = df['Score'].fillna(df['Score'].mean())
print(df)

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

**SECTION B**

**Q11.** Data Loading and Exploration


Load student_performance.csv into a Pandas DataFrame.
Perform the following:
Display the first 5 records.
Display the last 5 records.
Find the number of rows and columns.
Display the column names.
Display the data types.
Generate a statistical summary of the numerical columns

In [66]:
filepath = 'student_performance.csv'
df = pd.read_csv(filepath)
print(df.head(5))

  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9

In [65]:
print("Last 5 records:", df.tail(5))

Last 5 records:    Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

In [67]:
print("Number of rows and columns:", df.shape)

Number of rows and columns: (80, 11)

In [68]:
print("Column names:", df.columns)

Column names: Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

In [69]:
print("Data types:", df.dtypes)

Data types: Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

In [70]:
print("Statistical summary of numerical columns:")
display(df.describe())

Statistical summary of numerical columns:

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

**Q12.** Filtering and Sorting

Using the student dataset:
Find students whose Final_Score is greater than 75.
Find students whose Attendance is below 75%.
Find students from the Data Science department with Final_Score greater than 80.
Sort all students by Final_Score from highest to lowest.

In [73]:
print("Students with the Score > 75 : ", df[df['Final_Score'] > 75])

Students with the Score > 75 :     Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

In [78]:
print("Students with Attendance < 75%:", df[df['Attendance'] < 75])

Students with Attendance < 75%:    Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

In [80]:
print("Data Science students with Final Score > 80:", df[(df['Department'] == 'Data Science') & (df['Final_Score'] > 80)])

Data Science students with Final Score > 80:    Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

In [79]:
print("Students sorted by Final Score (Highest to Lowest):", df.sort_values(by='Final_Score', ascending=False))

Students sorted by Final Score (Highest to Lowest):    Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

**Q13.** Feature Creation

Create a new column called:
Average_Technical_Score
Calculate it using:
Python_Score
SQL_Score
Pandas_Score
NumPy_Score
Then create another column called:
Performance
using these rules:
Average Technical Score Performance
>= 90 Excellent
>= 75 Good
>= 60 Average
< 60 Needs Improvement
Display the resulting DataFrame.

In [82]:
technical_cols = ['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']
df['Average_Technical_Score'] = df[technical_cols].mean(axis=1)
def get_performance(score):
    if score >= 90:
        return 'Excellent'
    elif score >= 75:
        return 'Good'
    elif score >= 60:
        return 'Average'
    else:
        return 'Needs Improvement'
df['Performance'] = df['Average_Technical_Score'].apply(get_performance)
display(df[['Name'] + technical_cols + ['Average_Technical_Score', 'Performance']].head(10))

,Name,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Average_Technical_Score,Performance
0,Rahul Varma,89.4,86.3,81.9,76.7,83.575,Good
1,Kiran Pillai,70.3,63.1,65.1,62.3,65.200,Average
2,Fathima Joseph,79.9,80.4,65.3,68.0,73.400,Average
3,Rahul Sharma,65.8,50.7,52.6,48.8,54.475,Needs Improvement
4,Asha Nair,90.1,82.9,72.4,87.7,83.275,Good
5,Diya Reddy,52.0,78.1,47.8,58.9,59.200,Needs Improvement
6,Akhil Varma,81.7,82.2,81.5,64.2,77.400,Good
7,Akhil Varma,72.1,80.4,72.9,73.5,74.725,Average
8,Diya Menon,94.8,86.0,87.7,100.0,92.125,Excellent
9,Gokul Pillai,79.6,85.0,74.1,80.5,79.800,Good

**Q14.** GroupBy Analysis


Using the student dataset, calculate the following for each department:
Number of students
Average Final Score
Maximum Final Score
Minimum Final Score
Sort the resulting DataFrame by Average Final Score in descending order.

In [87]:
df['Department'] = df['Department'].str.strip().str.title()
groupby_df = df.groupby('Department')['Final_Score'].agg(
    Number_of_Students='count',
    Average_Final_Score='mean',
    Maximum_Final_Score='max',
    Minimum_Final_Score='min'
).reset_index()
sorted_groupby_df = groupby_df.sort_values(by='Average_Final_Score', ascending=False)
display(sorted_groupby_df)

,Department,Number_of_Students,Average_Final_Score,Maximum_Final_Score,Minimum_Final_Score
3,Electronics,13,72.846154,86.9,51.2
1,Computer Science,30,70.653333,96.0,40.6
2,Data Science,27,70.559259,97.0,43.5
0,Commerce,8,67.825000,83.7,54.6

**Q15.** NumPy and Pandas Integration


Using the student dataset:
Convert the Final_Score column into a NumPy array.
Calculate using NumPy:
Mean
Median
Standard deviation
25th percentile
75th percentile
Identify all students whose Final_Score is above the overall mean.

In [91]:
scores_array = df['Final_Score'].to_numpy()
mean = np.nanmean(scores_array)
median = np.nanmedian(scores_array)
std = np.nanstd(scores_array)
percentile_25 = np.nanpercentile(scores_array, 25)
percentile_75 = np.nanpercentile(scores_array, 75)
print("NumPy Statistical Calculation")
print(f"Mean: {overall_mean:.2f}")
print(f"Median: {overall_median:.2f}")
print(f"Standard Deviation: {overall_std:.2f}")
print(f"25th Percentile: {percentile_25:.2f}")
print(f"75th Percentile: {percentile_75:.2f}")
above_mean_df = df[df['Final_Score'] > overall_mean]
print(f"Students with Final_Score above the overall mean ({overall_mean:.2f}):")
display(above_mean_df[['Name', 'Department', 'Final_Score']])

NumPy Statistical Calculation
Mean: 70.70
Median: 70.95
Standard Deviation: 13.96
25th Percentile: 60.45
75th Percentile: 82.28
Students with Final_Score above the overall mean (70.70):

              Name        Department  Final_Score
0      Rahul Varma  Computer Science         82.7
4        Asha Nair      Data Science         81.9
6      Akhil Varma       Electronics         77.0
7      Akhil Varma  Computer Science         79.2
8       Diya Menon      Data Science         83.0
9     Gokul Pillai  Computer Science         73.8
10        Diya Das      Data Science         91.9
11      Arun Reddy       Electronics         86.9
16    Rahul Thomas      Data Science         91.1
17      Priya Nair      Data Science         75.1
20      Arun Varma          Commerce         73.2
23  Fathima Joseph          Commerce         83.7
24     Kiran Varma       Electronics         77.3
27     Nikhil Nair      Data Science         77.1
30      Amal Varma  Computer Science         85.5
33        Amal Das  Computer Science         84.3
35      Maya Menon       Electronics         84.2
37    Kiran Pillai       Electronics         82.4
39    Rohan Sharma  Computer Science         78.5
40     Amal Pillai  Computer Science         94.5
41     Arun Joseph  Computer Science         77.9
43       Rahul Das  Computer Science         77.3
46       Gokul Das      Data Science         74.8
47     Priya Kumar      Data Science         77.3
48     Asha Sharma      Data Science         97.0
51      Gokul Nair          Commerce         79.3
52      Maya Varma  Computer Science         71.0
55     Vivek Varma      Data Science         93.3
56    Rohan Pillai          Commerce         75.2
57     Diya Thomas  Computer Science         92.3
58       Anu Menon       Electronics         84.9
59      Asha Menon      Data Science         87.9
60  Fathima Sharma  Computer Science         70.8
61    Kiran Pillai  Computer Science         96.0
64    Rohan Sharma  Computer Science         83.5
66    Rahul Thomas      Data Science         70.7
67        Maya Das  Computer Science         83.7
72   Swathi Joseph      Data Science         73.5
73       Anu Kumar  Computer Science         83.4
74      Gokul Nair      Data Science         70.9
77  Fathima Sharma  Computer Science         75.2
79      Diya Varma       Electronics         78.6

**SECTION C**

**Q16.** Student Performance Analysis
Use student_performance.csv .

**A.** Data Cleaning – 2 Marks
Identify missing values.
Handle missing numerical values appropriately.

In [93]:
filepath = 'student_performance.csv'
df = pd.read_csv(filepath)
print(df.isnull().sum())
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())
print(df)

Student_ID      0
Name            0
Gender          0
Department      0
Age             3
Attendance      3
Python_Score    2
SQL_Score       0
Pandas_Score    2
NumPy_Score     2
Final_Score     2
dtype: int64
   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score
0          82.7
1          60.3
2          67.1
3          57.2
4          81.9
..          ...
75         47.2
76         43.5
77         75.2
78         63.4
79         78.6

[80 rows x 11 columns]

**B.** Feature Engineering

Create a column:
Average_Score
using the Python, SQL, Pandas and NumPy scores.
Create another column:
Pass_Status
using:
Average_Score >= 50 → Pass
Average_Score < 50 → Fail

**C.** Analysis
Find:
Top 5 students based on Average_Score .
Department having the highest average score.
Average attendance by department.
Number of students who passed and failed.

In [95]:
print(df.sort_values(by='Average_Score', ascending=False)[['Name', 'Average_Score']].head(5))

            Name  Average_Score
10      Diya Das         95.625
61  Kiran Pillai         95.200
8     Diya Menon         92.125
16  Rahul Thomas         89.350
35    Maya Menon         87.800

In [96]:
print(df.groupby('Department')['Average_Score'].mean().sort_values(ascending=False).head(1))

Department
Electronics    74.063462
Name: Average_Score, dtype: float64

In [97]:
print(df.groupby('Department')['Attendance'].mean())

Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.768025
Computer science    92.100000
Data Science        82.076768
Electronics         80.576923
data science        81.672727
Name: Attendance, dtype: float64

In [98]:
print(df['Pass_Status'].value_counts())

Pass_Status
Pass    72
Fail     8
Name: count, dtype: int64

**D.** Summary
Create a summary DataFrame containing:
Department
Total_Students
Average_Score
Average_Attendance
Pass_Count
Fail_Count

In [100]:
summary_df = df.groupby('Department').agg(
    Total_Students=('Name', 'count'),
    Average_Score=('Average_Score', 'mean'),
    Average_Attendance=('Attendance', 'mean'),
    Pass_Count=('Pass_Status', lambda x: (x == 'Pass').sum()),
    Fail_Count=('Pass_Status', lambda x: (x == 'Fail').sum())
).reset_index()
print(summary_df)

         Department  Total_Students  Average_Score  Average_Attendance  \
0     Data Science                1      59.200000           76.700000
1          Commerce               8      68.806931           77.437500
2  Computer Science              29      70.515296           82.768025
3  Computer science               1      53.843590           92.100000
4      Data Science              27      70.671783           82.076768
5       Electronics              13      74.063462           80.576923
6      data science               1      64.725000           81.672727

   Pass_Count  Fail_Count
0           1           0
1           8           0
2          24           5
3           1           0
4          24           3
5          13           0
6           1           0

**Q17.** Sales Data Analysis

**A.** Data Preparation

Load the CSV file.
Convert Order_Date into an appropriate Pandas datetime type.
Check for missing values and handle them appropriately.

In [109]:
filepath = 'sales.csv'
df = pd.read_csv(filepath)
print("Missing values:")
print(df.isnull().sum())
df = df.dropna()
print("Cleaned DataFrame Preview:")
display(df.head())

Missing values:
Order_ID      0
Order_Date    0
Product       0
Category      0
Region        1
Sales         0
Quantity      1
Discount      0
Profit        1
dtype: int64
Cleaned DataFrame Preview:

,Order_ID,Order_Date,Product,Category,Region,Sales,Quantity,Discount,Profit
0,ORD5001,2026-06-10,Office Chair,Furniture,East,142.1,1.0,0.02,12.78
1,ORD5002,2026-04-25,USB Hub,Accessories,North,51.52,2.0,0.08,4.57
2,ORD5003,2026-03-07,Monitor,Computers,West,648.0,4.0,0.1,86.32
3,ORD5004,2026-03-19,Office Chair,Furniture,North,290.0,2.0,0.0,47.77
4,ORD5005,2026-01-25,Tablet,Computers,North,304.0,1.0,0.05,23.43

**B.** Sales Analysis
Calculate:
Total sales
Total profit
Average sales
Top 5 products based on sales
Region generating the highest sales

In [122]:
print(f"Total Sales : ", df['Sales'].sum())
print(f"Total Profit : ", df['Profit'].sum())
print(f"Average Sales : ", df['Sales'].mean())
print("Top 5 Products by Sales", top_5_products, "\n")
top_5_products = df.groupby('Product')['Sales'].sum().nlargest(5)
highest_sales_region = df.groupby('Region')['Sales'].sum().idxmax()
print(f"Region generating the highest sales : ", highest_sales_region)

Total Sales :  93712.94
Total Profit :  15096.689999999999
Average Sales :  529.4516384180791
Top 5 Products by Sales Product
Laptop        33995.0
Printer       13719.3
Tablet        10291.2
Monitor        9148.9
Headphones     5765.5
Name: Sales, dtype: float64

Region generating the highest sales :  West

**C.** Category Analysis

Create a summary containing:
Category
Total Sales
Total Profit
Average Discount
Sort the result by Total Sales in descending order.